{{- if .Values.azureFileSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azureFileSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.azureFileSecret.storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.azureFileSecret.storageAccountKey | b64enc }}
{{- end }}
