apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BOOT_MODE
              value: "{{ .Values.env.BOOT_MODE }}"
            - name: DEBUG
              value: "{{ .Values.env.DEBUG }}"
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          volumeMounts:
            {{- range .Values.azureFileShares }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
      volumes:
        {{- range .Values.azureFileShares }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: pvc-{{ .name }}
        {{- end }}
