apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: win-ingressroute
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/aaa`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.web.port }}
