{{- range .Values.azureFileShares }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  capacity:
    storage: {{ .size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: {{ $.Values.azureFileSecret.name }}#{{ .shareName }}
    volumeAttributes:
      shareName: {{ .shareName }}
      storageAccount: {{ $.Values.azureFileSecret.name }}
    nodeStageSecretRef:
      name: {{ $.Values.azureFileSecret.name }}
      namespace: {{ $.Values.namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
