[project]
name = "echo-server-omniparser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ken Chau", email = "kchau@microsoft.com" }
]
requires-python = ">=3.12"
dependencies = [
    "easyocr>=1.7.2",
    "fastapi>=0.115.10",
    "numpy==1.26.4",
    "openai>=1.64.0",
    "opencv-python>=4.8.1.78",
    "paddleocr>=2.9.1",
    "paddlepaddle>=3.0.0rc1",
    "supervision>=0.24.0",
    "torch>=2.2.0",
    "torchvision>=0.21.0",
    "transformers>=4.46.1",
    "ultralytics>=8.3.80",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/server_omniparser"]

[tool.uv]
override-dependencies = ["protobuf>=3.20.1"]
