services:
  windowscomputer:
    container_name: windowscomputer
    image: lukaskellerstein/windows-computer:0.0.2
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 5000:5000
      - 6000:6000
    volumes:
      - ./iso/win.iso:/custom.iso
      - ./scripts:/oem
      - ./data:/data
      - ./storage:/storage
    restart: always
    stop_grace_period: 2m
