[project]
name = "echo-operator-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ken Chau", email = "kchau@microsoft.com" }
]
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.13.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/echo_operator_ui"]
