apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tempcomputer-ingressroute
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/bbb`)
      kind: Rule
      services:
        - name: windows
          port: 8006
