[project]
name = "echo-operator-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "huggingface-hub>=0.29.1",
]

[project.scripts]
project = "cli.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/cli"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"